
package edu.up.bsi.cardapio.soap.server;

import java.util.Date;
import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FuncoesWS", targetNamespace = "http://server.soap.cardapio.bsi.up.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FuncoesWS {


    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "login_usuario")
    @WebResult(name = "login_usuario_resultado", targetNamespace = "")
    @RequestWrapper(localName = "login_usuario", targetNamespace = "http://server.soap.cardapio.bsi.up.edu/", className = "edu.up.bsi.cardapio.soap.server.LoginUsuario")
    @ResponseWrapper(localName = "login_usuarioResponse", targetNamespace = "http://server.soap.cardapio.bsi.up.edu/", className = "edu.up.bsi.cardapio.soap.server.LoginUsuarioResponse")
    @Action(input = "http://server.soap.cardapio.bsi.up.edu/FuncoesWS/login_usuarioRequest", output = "http://server.soap.cardapio.bsi.up.edu/FuncoesWS/login_usuarioResponse")
    public boolean loginUsuario();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "um_alimento")
    @WebResult(name = "um_alimento_resultado", targetNamespace = "")
    @RequestWrapper(localName = "um_alimento", targetNamespace = "http://server.soap.cardapio.bsi.up.edu/", className = "edu.up.bsi.cardapio.soap.server.UmAlimento")
    @ResponseWrapper(localName = "um_alimentoResponse", targetNamespace = "http://server.soap.cardapio.bsi.up.edu/", className = "edu.up.bsi.cardapio.soap.server.UmAlimentoResponse")
    @Action(input = "http://server.soap.cardapio.bsi.up.edu/FuncoesWS/um_alimentoRequest", output = "http://server.soap.cardapio.bsi.up.edu/FuncoesWS/um_alimentoResponse")
    public String umAlimento(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<edu.up.bsi.cardapio.soap.server.AlimentoCardapio>
     */
    @WebMethod(operationName = "todos_alimentos")
    @WebResult(name = "todos_alimentos_resultado", targetNamespace = "")
    @RequestWrapper(localName = "todos_alimentos", targetNamespace = "http://server.soap.cardapio.bsi.up.edu/", className = "edu.up.bsi.cardapio.soap.server.TodosAlimentos")
    @ResponseWrapper(localName = "todos_alimentosResponse", targetNamespace = "http://server.soap.cardapio.bsi.up.edu/", className = "edu.up.bsi.cardapio.soap.server.TodosAlimentosResponse")
    @Action(input = "http://server.soap.cardapio.bsi.up.edu/FuncoesWS/todos_alimentosRequest", output = "http://server.soap.cardapio.bsi.up.edu/FuncoesWS/todos_alimentosResponse")
    public List<AlimentoCardapio> todosAlimentos();

    /**
     * 
     * @return
     *     returns java.util.Date
     */
  
    @WebMethod(operationName = "hora_atual")
    @WebResult(name = "hora_atual_resultado", targetNamespace = "")
    @RequestWrapper(localName = "hora_atual", targetNamespace = "http://server.soap.cardapio.bsi.up.edu/", className = "edu.up.bsi.cardapio.soap.server.HoraAtual")
    @ResponseWrapper(localName = "hora_atualResponse", targetNamespace = "http://server.soap.cardapio.bsi.up.edu/", className = "edu.up.bsi.cardapio.soap.server.HoraAtualResponse")
    @Action(input = "http://server.soap.cardapio.bsi.up.edu/FuncoesWS/hora_atualRequest", output = "http://server.soap.cardapio.bsi.up.edu/FuncoesWS/hora_atualResponse")
    public Date horaAtual();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "dados_empresa")
    @WebResult(name = "dados_empresa_resultado", targetNamespace = "")
    @RequestWrapper(localName = "dados_empresa", targetNamespace = "http://server.soap.cardapio.bsi.up.edu/", className = "edu.up.bsi.cardapio.soap.server.DadosEmpresa")
    @ResponseWrapper(localName = "dados_empresaResponse", targetNamespace = "http://server.soap.cardapio.bsi.up.edu/", className = "edu.up.bsi.cardapio.soap.server.DadosEmpresaResponse")
    @Action(input = "http://server.soap.cardapio.bsi.up.edu/FuncoesWS/dados_empresaRequest", output = "http://server.soap.cardapio.bsi.up.edu/FuncoesWS/dados_empresaResponse")
    public String dadosEmpresa(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
