
package edu.up.bsi.cardapio.soap.server;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FuncoesWS", targetNamespace = "http://server.soap.cardapio.bsi.up.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FuncoesWS {


    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "login_usuario")
    @WebResult(name = "login_usuario_resultado", targetNamespace = "")
    @RequestWrapper(localName = "login_usuario", targetNamespace = "http://server.soap.cardapio.bsi.up.edu/", className = "edu.up.bsi.cardapio.soap.server.LoginUsuario")
    @ResponseWrapper(localName = "login_usuarioResponse", targetNamespace = "http://server.soap.cardapio.bsi.up.edu/", className = "edu.up.bsi.cardapio.soap.server.LoginUsuarioResponse")
    @Action(input = "http://server.soap.cardapio.bsi.up.edu/FuncoesWS/login_usuarioRequest", output = "http://server.soap.cardapio.bsi.up.edu/FuncoesWS/login_usuarioResponse")
    public boolean loginUsuario();

    /**
     * 
     * @return
     *     returns java.util.List<edu.up.bsi.cardapio.soap.server.AlimentoCardapio>
     */
    @WebMethod(operationName = "todos_alimentos")
    @WebResult(name = "todos_alimentos_resultado", targetNamespace = "")
    @RequestWrapper(localName = "todos_alimentos", targetNamespace = "http://server.soap.cardapio.bsi.up.edu/", className = "edu.up.bsi.cardapio.soap.server.TodosAlimentos")
    @ResponseWrapper(localName = "todos_alimentosResponse", targetNamespace = "http://server.soap.cardapio.bsi.up.edu/", className = "edu.up.bsi.cardapio.soap.server.TodosAlimentosResponse")
    @Action(input = "http://server.soap.cardapio.bsi.up.edu/FuncoesWS/todos_alimentosRequest", output = "http://server.soap.cardapio.bsi.up.edu/FuncoesWS/todos_alimentosResponse")
    public List<AlimentoCardapio> todosAlimentos();

}
